name: Build Android Release

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        npm install
        npm install -g react-native-cli

    - name: Build Android Release
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: android/app/build/outputs/apk/release/app-release.apk